修改了个人主页搜索视频为空时的报错反馈
ywmoyue/biliuwp-lite pull request #457
Opened 2023-12-25 04:11 UTC by GD-Slime

fix #426 
搜索关键字不存在于up主上传的视频列表导致的。
调整的可能有点问题，如果不行请修改。

2023-12-31 02:04 UTC, ywmoyue requested changes

2023-12-31 02:04 UTC, ywmoyue commented on src/BiliLite.UWP/Services/GrpcService.cs
> +                throw new CustomizedErrorException("(っ °Д °;)っ 没有找到相应的视频~");
建议新加一个NotFoundException

2023-12-31 04:16 UTC, GD-Slime commented
@ywmoyue 有点小冲突，解决一下应该就可以合并了

2024-01-01 02:28 UTC, ywmoyue approved these changes

2024-01-01 02:32 UTC, merged