直播间 抽奖、弹幕延迟、醒目留言、舰长信息、各类其他小问题综合修复与优化
ywmoyue/biliuwp-lite pull request #651
Opened 2024-05-27 05:21 UTC by GD-Slime

1. 红包/天选实际加入api 5cce86e6 fix #566 
2. 央视新闻等官方直播间有问题 90c11d6c fix #647 
3. 自己弹幕加框 3a0ba220 
4. 自己和主播的弹幕特殊化 328bd45b 
5. 弹幕延迟修复 79fd1df6 fix #633 
6. 个人主页点击进入直播间按钮fix 8bdc79ba fix (在无直播间的用户主页还能看到直播间按钮)
7. 区别续费与新舰长 c1a96f6a 
8. 支持调整对齐方式 1299633c 
9. SuperChat加入弹幕与chatList & 天选红包信息加入屏蔽 & 禁言观众历史发言展示 & chat栏自动滚动优化 2a4b1826

commit是后分的……可能单独查看某一commit会有问题。可能还有我忘记写出来的功能优化什么的……

2024-05-29 02:43 UTC, GD-Slime commented
@ywmoyue 先不着急合并，我这里发现天选抽奖的api返回的平时用不着的几个值的意义似乎和之前认为的不一样。 我改一下吧

2024-05-29 03:04 UTC, ywmoyue commented
@GD-Slime 好的，我这边还没看完

2024-05-29 06:40 UTC, GD-Slime commented
@ywmoyue 应该可以了，虽然说天选抽奖的部分比较难以测试

2024-05-29 06:42 UTC, GD-Slime commented
@ywmoyue 可以了，虽然说天选抽奖新加的部分比较难测试到底是否有效…

2024-05-30 13:45 UTC, ywmoyue requested changes
看完发现几个小问题，麻烦修改下吧

2024-05-30 13:45 UTC, ywmoyue commented on src/BiliLite.UWP/Pages/LiveDetailPage.xaml.cs
> +                if (_ is LiveRoomAnchorLotteryInfoModel) m_liveRoomViewModel.LotteryDanmu["AnchorLottery"] = (_ as LiveRoomAnchorLotteryInfoModel).Danmu;
这个`_`变量这里要用的话需要给一个有意义的变量名，`sender`也行

2024-05-31 05:39 UTC, GD-Slime commented
@ywmoyue 已修改

2024-06-01 02:25 UTC, ywmoyue approved these changes

2024-06-01 02:26 UTC, merged

2024-06-01 03:49 UTC, ywmoyue commented
该PR改动涉及有点多这边先给临时版本发布一下，正式版本发布时再详细写Changedlog