分离主题颜色
ywmoyue/biliuwp-lite pull request #928
Opened 2024-11-29 09:50 UTC by ProJend

为自定义主题色提供模板

2024-11-29 10:03 UTC, ProJend commented on src/BiliLite.UWP/App.xaml
> +                <ResourceDictionary Source="Themes/Pink.xaml" />
后期需要手动选择颜色资源文件

2024-12-01 03:59 UTC, ywmoyue requested changes

2024-12-02 09:02 UTC, ProJend commented on src/BiliLite.UWP/MainPage.xaml.cs
> +            var styleKvp = dict.FirstOrDefault(x => x.Key.ToString().Contains("muxc:TabViewItem"));
调试报错，当时需要频繁配置`XamlControlsResources`，无法识别`TabViewItem`

2024-12-02 10:33 UTC, ywmoyue approved these changes

2024-12-02 12:07 UTC, ywmoyue commented
好的，感谢大佬的PR

2024-12-02 12:07 UTC, merged